[package]
name = "table_of_chairs"
version = "0.1.0"
edition = "2021"

[dependencies]
assert_cmd = "2.0.16"
cli-table = "0.4.9"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"

[dev-dependencies]

